export default {
  active: {
    bike: 'Bike',
    run: 'Go for a Run',
    walk: 'Take a Walk',
    yoga: 'Do Yoga',
    class: 'Take a Workout Class'
  },
  chill: {
    park: 'Chill in the Park',
    movie: 'Watch a Movie'
  },
  restaurant: {
    afghani: 'Afghan',
    african: 'African',
    senegalese: 'Senegalese',
    'south+african': 'South African',
    'new+american': 'American (New)',
    american: 'American (Traditional)',
    arabian: 'Arabian',
    argentine: 'Argentine',
    armenian: 'Armenian',
    'asian+fusion': 'Asian Fusion',
    australian: 'Australian',
    austrian: 'Austrian',
    bangladeshi: 'Bangladeshi',
    bbq: 'Barbeque',
    basque: 'Basque',
    belgian: 'Belgian',
    brasseries: 'Brasseries',
    brazilian: 'Brazilian',
    'breakfast+brunch': 'Breakfast & Brunch',
    pancakes: 'Pancakes',
    british: 'British',
    buffets: 'Buffets',
    bulgarian: 'Bulgarian',
    burgers: 'Burgers',
    burmese: 'Burmese',
    cafes: 'Cafes',
    cafeteria: 'Cafeteria',
    cajun: 'Cajun/Creole',
    cambodian: 'Cambodian',
    caribbean: 'Caribbean',
    dominican: 'Dominican',
    haitian: 'Haitian',
    'puerto+rican': 'Puerto Rican',
    trinidadian: 'Trinidadian',
    catalan: 'Catalan',
    cheesesteaks: 'Cheesesteaks',
    chickenshop: 'Chicken Shop',
    'chicken+wings': 'Chicken Wings',
    chinese: 'Chinese',
    cantonese: 'Cantonese',
    dimsum: 'Dim Sum',
    hainan: 'Hainan',
    shanghainese: 'Shanghainese',
    szechuan: 'Szechuan',
    'comfort+food': 'Comfort Food',
    creperies: 'Creperies',
    cuban: 'Cuban',
    czech: 'Czech',
    delis: 'Delis',
    diners: 'Diners',
    eritrean: 'Eritrean',
    ethiopian: 'Ethiopian',
    hotdogs: 'Fast Food',
    filipino: 'Filipino',
    fishnchips: 'Fish & Chips',
    fondue: 'Fondue',
    foodstands: 'Food Stands',
    french: 'French',
    mauritius: 'Mauritius',
    gastropubs: 'Gastropubs',
    georgian: 'Georgian',
    german: 'German',
    'gluten+free': 'Gluten-Free',
    greek: 'Greek',
    guamanian: 'Guamanian',
    halal: 'Halal',
    hawaiian: 'Hawaiian',
    himalayan: 'Himalayan/Nepalese',
    honduran: 'Honduran',
    hotdog: 'Hot Dogs',
    hotpot: 'Hot Pot',
    hungarian: 'Hungarian',
    iberian: 'Iberian',
    indpak: 'Indian',
    indonesian: 'Indonesian',
    irish: 'Irish',
    italian: 'Italian',
    calabrian: 'Calabrian',
    sardinian: 'Sardinian',
    sicilian: 'Sicilian',
    tuscan: 'Tuscan',
    japanese: 'Japanese',
    izakaya: 'Izakaya',
    'japanese+curry': 'Japanese Curry',
    ramen: 'Ramen',
    teppanyaki: 'Teppanyaki',
    kebab: 'Kebab',
    korean: 'Korean',
    kosher: 'Kosher',
    laotian: 'Laotian',
    latin: 'Latin American',
    colombian: 'Colombian',
    salvadoran: 'Salvadoran',
    venezuelan: 'Venezuelan',
    'raw+food': 'Live/Raw Food',
    malaysian: 'Malaysian',
    mediterranean: 'Mediterranean',
    falafel: 'Falafel',
    mexican: 'Mexican',
    tacos: 'Tacos',
    'middle+eastern': 'Middle Eastern',
    egyptian: 'Egyptian',
    lebanese: 'Lebanese',
    'modern+european': 'Modern European',
    mongolian: 'Mongolian',
    moroccan: 'Moroccan',
    'new+mexican': 'New Mexican Cuisine',
    nicaraguan: 'Nicaraguan',
    noodles: 'Noodles',
    pakistani: 'Pakistani',
    panasian: 'Pan Asian',
    persian: 'Persian/Iranian',
    peruvian: 'Peruvian',
    pizza: 'Pizza',
    polish: 'Polish',
    polynesian: 'Polynesian',
    portuguese: 'Portuguese',
    poutineries: 'Poutineries',
    russian: 'Russian',
    salad: 'Salad',
    sandwiches: 'Sandwiches',
    scandinavian: 'Scandinavian',
    scottish: 'Scottish',
    seafood: 'Seafood',
    singaporean: 'Singaporean',
    slovakian: 'Slovakian',
    somali: 'Somali',
    soulfood: 'Soul Food',
    soup: 'Soup',
    southern: 'Southern',
    spanish: 'Spanish',
    srilankan: 'Sri Lankan',
    steak: 'Steakhouses',
    supperclubs: 'Supper Clubs',
    sushi: 'Sushi Bars',
    syrian: 'Syrian',
    taiwanese: 'Taiwanese',
    tapas: 'Tapas',
    'tex-mex': 'Tex-Mex',
    thai: 'Thai',
    turkish: 'Turkish',
    ukrainian: 'Ukrainian',
    uzbek: 'Uzbek',
    vegan: 'Vegan',
    vegetarian: 'Vegetarian',
    vietnamese: 'Vietnamese',
    waffles: 'Waffles',
    wraps: 'Wraps'
  }
}
