export default {
  active: {
    bike: {searchStr: 'bike', displayName: 'Bike'},
    run: {searchStr: 'run', displayName: 'Go for a Run'},
    walk: {searchStr: 'walk', displayName: 'Take a Walk'},
    yoga: {searchStr: 'yoga', displayName: 'Do Yoga'},
    class: {searchStr: 'class', displayName: 'Take a Workout Class'}
  },
  chill: {
    park: {searchStr: 'park', displayName: 'Chill in the Park'},
    movie: {searchStr: 'movie', displayName: 'Watch a Movie'}
  },
  restaurant: {
    afghani: {searchStr: 'afghani', displayName: 'Afghan'},
    african: {searchStr: 'african', displayName: 'African'},
    senegalese: {searchStr: 'senegalese', displayName: 'Senegalese'},
    'south+african': {searchStr: 'south+african', displayName: 'South African'},
    'new+american': {searchStr: 'new+american', displayName: 'American (New)'},
    american: {searchStr: 'american', displayName: 'American (Traditional)'},
    arabian: {searchStr: 'arabian', displayName: 'Arabian'},
    argentine: {searchStr: 'argentine', displayName: 'Argentine'},
    armenian: {searchStr: 'armenian', displayName: 'Armenian'},
    'asian+fusion': {searchStr: 'asian+fusion', displayName: 'Asian Fusion'},
    australian: {searchStr: 'australian', displayName: 'Australian'},
    austrian: {searchStr: 'austrian', displayName: 'Austrian'},
    bangladeshi: {searchStr: 'bangladeshi', displayName: 'Bangladeshi'},
    bbq: {searchStr: 'bbq', displayName: 'Barbeque'},
    basque: {searchStr: 'basque', displayName: 'Basque'},
    belgian: {searchStr: 'belgian', displayName: 'Belgian'},
    brasseries: {searchStr: 'brasseries', displayName: 'Brasseries'},
    brazilian: {searchStr: 'brazilian', displayName: 'Brazilian'},
    'breakfast+brunch': {
      searchStr: 'breakfast+brunch',
      displayName: 'Breakfast & Brunch'
    },
    pancakes: {searchStr: 'pancakes', displayName: 'Pancakes'},
    british: {searchStr: 'british', displayName: 'British'},
    buffets: {searchStr: 'buffets', displayName: 'Buffets'},
    bulgarian: {searchStr: 'bulgarian', displayName: 'Bulgarian'},
    burgers: {searchStr: 'burgers', displayName: 'Burgers'},
    burmese: {searchStr: 'burmese', displayName: 'Burmese'},
    cafes: {searchStr: 'cafes', displayName: 'Cafes'},
    cafeteria: {searchStr: 'cafeteria', displayName: 'Cafeteria'},
    cajun: {searchStr: 'cajun', displayName: 'Cajun/Creole'},
    cambodian: {searchStr: 'cambodian', displayName: 'Cambodian'},
    caribbean: {searchStr: 'caribbean', displayName: 'Caribbean'},
    dominican: {searchStr: 'dominican', displayName: 'Dominican'},
    haitian: {searchStr: 'haitian', displayName: 'Haitian'},
    'puerto+rican': {searchStr: 'puerto+rican', displayName: 'Puerto Rican'},
    trinidadian: {searchStr: 'trinidadian', displayName: 'Trinidadian'},
    catalan: {searchStr: 'catalan', displayName: 'Catalan'},
    cheesesteaks: {searchStr: 'cheesesteaks', displayName: 'Cheesesteaks'},
    chickenshop: {searchStr: 'chickenshop', displayName: 'Chicken Shop'},
    'chicken+wings': {searchStr: 'chicken+wings', displayName: 'Chicken Wings'},
    chinese: {searchStr: 'chinese', displayName: 'Chinese'},
    cantonese: {searchStr: 'cantonese', displayName: 'Cantonese'},
    dimsum: {searchStr: 'dimsum', displayName: 'Dim Sum'},
    hainan: {searchStr: 'hainan', displayName: 'Hainan'},
    shanghainese: {searchStr: 'shanghainese', displayName: 'Shanghainese'},
    szechuan: {searchStr: 'szechuan', displayName: 'Szechuan'},
    'comfort+food': {searchStr: 'comfort+food', displayName: 'Comfort Food'},
    creperies: {searchStr: 'creperies', displayName: 'Creperies'},
    cuban: {searchStr: 'cuban', displayName: 'Cuban'},
    czech: {searchStr: 'czech', displayName: 'Czech'},
    delis: {searchStr: 'delis', displayName: 'Delis'},
    diners: {searchStr: 'diners', displayName: 'Diners'},
    eritrean: {searchStr: 'eritrean', displayName: 'Eritrean'},
    ethiopian: {searchStr: 'ethiopian', displayName: 'Ethiopian'},
    hotdogs: {searchStr: 'hotdogs', displayName: 'Fast Food'},
    filipino: {searchStr: 'filipino', displayName: 'Filipino'},
    'fish+chips': {searchStr: 'fish+chips', displayName: 'Fish & Chips'},
    fondue: {searchStr: 'fondue', displayName: 'Fondue'},
    foodstands: {searchStr: 'foodstands', displayName: 'Food Stands'},
    french: {searchStr: 'french', displayName: 'French'},
    mauritius: {searchStr: 'mauritius', displayName: 'Mauritius'},
    gastropubs: {searchStr: 'gastropubs', displayName: 'Gastropubs'},
    georgian: {searchStr: 'georgian', displayName: 'Georgian'},
    german: {searchStr: 'german', displayName: 'German'},
    'gluten+free': {searchStr: 'gluten+free', displayName: 'Gluten-Free'},
    greek: {searchStr: 'greek', displayName: 'Greek'},
    guamanian: {searchStr: 'guamanian', displayName: 'Guamanian'},
    halal: {searchStr: 'halal', displayName: 'Halal'},
    hawaiian: {searchStr: 'hawaiian', displayName: 'Hawaiian'},
    himalayan: {searchStr: 'himalayan', displayName: 'Himalayan/Nepalese'},
    honduran: {searchStr: 'honduran', displayName: 'Honduran'},
    hotdog: {searchStr: 'hotdog', displayName: 'Hot Dogs'},
    hotpot: {searchStr: 'hotpot', displayName: 'Hot Pot'},
    hungarian: {searchStr: 'hungarian', displayName: 'Hungarian'},
    iberian: {searchStr: 'iberian', displayName: 'Iberian'},
    indpak: {searchStr: 'indpak', displayName: 'Indian'},
    indonesian: {searchStr: 'indonesian', displayName: 'Indonesian'},
    irish: {searchStr: 'irish', displayName: 'Irish'},
    italian: {searchStr: 'italian', displayName: 'Italian'},
    calabrian: {searchStr: 'calabrian', displayName: 'Calabrian'},
    sardinian: {searchStr: 'sardinian', displayName: 'Sardinian'},
    sicilian: {searchStr: 'sicilian', displayName: 'Sicilian'},
    tuscan: {searchStr: 'tuscan', displayName: 'Tuscan'},
    japanese: {searchStr: 'japanese', displayName: 'Japanese'},
    izakaya: {searchStr: 'izakaya', displayName: 'Izakaya'},
    'japanese+curry': {
      searchStr: 'japanese+curry',
      displayName: 'Japanese Curry'
    },
    ramen: {searchStr: 'ramen', displayName: 'Ramen'},
    teppanyaki: {searchStr: 'teppanyaki', displayName: 'Teppanyaki'},
    kebab: {searchStr: 'kebab', displayName: 'Kebab'},
    korean: {searchStr: 'korean', displayName: 'Korean'},
    kosher: {searchStr: 'kosher', displayName: 'Kosher'},
    laotian: {searchStr: 'laotian', displayName: 'Laotian'},
    latin: {searchStr: 'latin', displayName: 'Latin American'},
    colombian: {searchStr: 'colombian', displayName: 'Colombian'},
    salvadoran: {searchStr: 'salvadoran', displayName: 'Salvadoran'},
    venezuelan: {searchStr: 'venezuelan', displayName: 'Venezuelan'},
    'raw+food': {searchStr: 'raw+food', displayName: 'Live/Raw Food'},
    malaysian: {searchStr: 'malaysian', displayName: 'Malaysian'},
    mediterranean: {searchStr: 'mediterranean', displayName: 'Mediterranean'},
    falafel: {searchStr: 'falafel', displayName: 'Falafel'},
    mexican: {searchStr: 'mexican', displayName: 'Mexican'},
    tacos: {searchStr: 'tacos', displayName: 'Tacos'},
    'middle+eastern': {
      searchStr: 'middle+eastern',
      displayName: 'Middle Eastern'
    },
    egyptian: {searchStr: 'egyptian', displayName: 'Egyptian'},
    lebanese: {searchStr: 'lebanese', displayName: 'Lebanese'},
    'modern+european': {
      searchStr: 'modern+european',
      displayName: 'Modern European'
    },
    mongolian: {searchStr: 'mongolian', displayName: 'Mongolian'},
    moroccan: {searchStr: 'moroccan', displayName: 'Moroccan'},
    'new+mexican': {
      searchStr: 'new+mexican',
      displayName: 'New Mexican Cuisine'
    },
    nicaraguan: {searchStr: 'nicaraguan', displayName: 'Nicaraguan'},
    noodles: {searchStr: 'noodles', displayName: 'Noodles'},
    pakistani: {searchStr: 'pakistani', displayName: 'Pakistani'},
    panasian: {searchStr: 'panasian', displayName: 'Pan Asian'},
    persian: {searchStr: 'persian', displayName: 'Persian/Iranian'},
    peruvian: {searchStr: 'peruvian', displayName: 'Peruvian'},
    pizza: {searchStr: 'pizza', displayName: 'Pizza'},
    polish: {searchStr: 'polish', displayName: 'Polish'},
    polynesian: {searchStr: 'polynesian', displayName: 'Polynesian'},
    portuguese: {searchStr: 'portuguese', displayName: 'Portuguese'},
    poutineries: {searchStr: 'poutineries', displayName: 'Poutineries'},
    russian: {searchStr: 'russian', displayName: 'Russian'},
    salad: {searchStr: 'salad', displayName: 'Salad'},
    sandwiches: {searchStr: 'sandwiches', displayName: 'Sandwiches'},
    scandinavian: {searchStr: 'scandinavian', displayName: 'Scandinavian'},
    scottish: {searchStr: 'scottish', displayName: 'Scottish'},
    seafood: {searchStr: 'seafood', displayName: 'Seafood'},
    singaporean: {searchStr: 'singaporean', displayName: 'Singaporean'},
    slovakian: {searchStr: 'slovakian', displayName: 'Slovakian'},
    somali: {searchStr: 'somali', displayName: 'Somali'},
    soulfood: {searchStr: 'soulfood', displayName: 'Soul Food'},
    soup: {searchStr: 'soup', displayName: 'Soup'},
    southern: {searchStr: 'southern', displayName: 'Southern'},
    spanish: {searchStr: 'spanish', displayName: 'Spanish'},
    srilankan: {searchStr: 'srilankan', displayName: 'Sri Lankan'},
    steak: {searchStr: 'steak', displayName: 'Steakhouses'},
    sushi: {searchStr: 'sushi', displayName: 'Sushi Bars'},
    syrian: {searchStr: 'syrian', displayName: 'Syrian'},
    taiwanese: {searchStr: 'taiwanese', displayName: 'Taiwanese'},
    tapas: {searchStr: 'tapas', displayName: 'Tapas'},
    'tex-mex': {searchStr: 'tex-mex', displayName: 'Tex-Mex'},
    thai: {searchStr: 'thai', displayName: 'Thai'},
    turkish: {searchStr: 'turkish', displayName: 'Turkish'},
    ukrainian: {searchStr: 'ukrainian', displayName: 'Ukrainian'},
    uzbek: {searchStr: 'uzbek', displayName: 'Uzbek'},
    vegan: {searchStr: 'vegan', displayName: 'Vegan'},
    vegetarian: {searchStr: 'vegetarian', displayName: 'Vegetarian'},
    vietnamese: {searchStr: 'vietnamese', displayName: 'Vietnamese'},
    waffles: {searchStr: 'waffles', displayName: 'Waffles'},
    wraps: {searchStr: 'wraps', displayName: 'Wraps'}
  }
}
