export default {
  nyc: {
    brooklyn: {
      'crown+heights': 'Crown Heights',
      flatbush: 'Flatbush',
      'prospect+park+': 'Prospect Park ',
      kensington: 'Kensington',
      brownsville: 'Brownsville',
      canarsie: 'Canarsie',
      'east+new+york': 'East New York',
      'highland+park': 'Highland Park',
      'bedford–stuyvesant': 'Bedford–Stuyvesant',
      bushwick: 'Bushwick',
      greenpoint: 'Greenpoint',
      williamsburg: 'Williamsburg',
      'brooklyn+heights': 'Brooklyn Heights',
      'brooklyn+navy+yard': 'Brooklyn Navy Yard',
      'cadman+plaza': 'Cadman Plaza',
      'clinton+hill': 'Clinton Hill',
      'downtown+brooklyn': 'Downtown Brooklyn',
      dumbo: 'DUMBO',
      'fort+greene': 'Fort Greene',
      'prospect+heights': 'Prospect Heights',
      'vinegar+hill': 'Vinegar Hill',
      'boerum+hill': 'Boerum Hill',
      'carroll+gardens': 'Carroll Gardens',
      'cobble+hill': 'Cobble Hill',
      gowanus: 'Gowanus',
      'park+slope': 'Park Slope',
      'red+hook': 'Red Hook',
      'barren+island': 'Barren Island',
      'bergen+beach': 'Bergen Beach',
      'coney+island': 'Coney Island',
      'brighton+beach': 'Brighton Beach',
      'manhattan+beach': 'Manhattan Beach',
      'sheepshead+bay+': 'Sheepshead Bay ',
      midwood: 'Midwood',
      flatlands: 'Flatlands',
      'gerritsen+beach': 'Gerritsen Beach',
      gravesend: 'Gravesend',
      'marine+park': 'Marine Park',
      'mill+basin': 'Mill Basin',
      'plumb+beach': 'Plumb Beach',
      'bay+ridge': 'Bay Ridge',
      bensonhurst: 'Bensonhurst',
      'borough+park': 'Borough Park',
      'dyker+heights': 'Dyker Heights',
      'sunset+park': 'Sunset Park'
    }
  }
}
